apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-tester.fullname" . }}
  labels:
    {{- include "api-tester.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      # 이렇게 추가해주기 port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "api-tester.selectorLabels" . | nindent 4 }}
